name: CI
on:
  push:
    branches: [ task8 ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: docker build -t task8 .
      - name: Test pygraphblas
        run: docker run --rm task8 python3 -m pytest tests/pygraphblas/test.py
      - name: Test pyformlang
        run: docker run --rm task8 python3 -m pytest tests/pyformlang/test.py
      - name: Test RPQ
        run: docker run --rm task8 python3 -m pytest tests/rpq/test.py
      - name: Test CYK
        run: docker run --rm task8 python3 -m pytest tests/cyk/test.py
      - name: Test CFPQ of Hellings
        run: docker run --rm task8 python3 -m pytest tests/cfpq/test.py
      - name: Test CFPQ through boolean matrices
        run: docker run --rm task8 python3 -m pytest tests/cfpq_bm/test.py
      - name: Test CFPQ through tensor product
        run: docker run --rm task8 python3 -m pytest tests/cfpq_tp/test.py
      - name: Test query language parser on program 1
        run: docker run --rm task8 ./correct_prog examples/program_1.txt
      - name: Test query language parser on program 2
        run: docker run --rm task8 ./correct_prog examples/program_2.txt
      - name: Test query language parser on program 3
        run: docker run --rm task8 ./correct_prog examples/program_3.txt
      - name: Test query language parser on program 4
        run: docker run --rm task8 ./correct_prog examples/program_4.txt
      - name: Test query language parser on program 5
        run: docker run --rm task8 ./correct_prog examples/program_5.txt
      - name: Test query language parser on no program 1
        run: docker run --rm task8 ./incorrect_prog examples/no_program_1.txt
      - name: Test query language parser on no program 2
        run: docker run --rm task8 ./incorrect_prog examples/no_program_2.txt
      - name: Test query language parser on no program 3
        run: docker run --rm task8 ./incorrect_prog examples/no_program_3.txt
      - name: Test query language parser on no program 4
        run: docker run --rm task8 ./incorrect_prog examples/no_program_4.txt
