name: CI
on:
  push:
    branches: [ task5 ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: docker build -t task5 .
      - name: Test CFPQ boolean matrix version
        run: docker run --rm task5 python3 -m pytest tests/cfpq_bm/test.py
      - name: Test CFPQ tensor product version
        run: docker run --rm task5 python3 -m pytest tests/cfpq_tp/test.py
