name: CI
on:
  push:
    branches: [ master ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: docker build -t task4 .
      - name: Test pygraphblas
        run: docker run --rm task4 python3 -m pytest tests/pygraphblas/test.py
      - name: Test pyformlang
        run: docker run --rm task4 python3 -m pytest tests/pyformlang/test.py
      - name: Test RPQ
        run: docker run --rm task4 python3 -m pytest tests/rpq/test.py
      - name: Test CYK
        run: docker run --rm task4 python3 -m pytest tests/cyk/test.py
      - name: Test CFPQ
        run: docker run --rm task4 python3 -m pytest tests/cfpq/test.py
