name: CI
on:
  push:
    branches: [ task4_2 ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: docker build -t task4_2 .
      - name: Test CYK
        run: docker run --rm task4_2 python3 -m pytest tests/cyk/test.py
      - name: Test CFPQ
        run: docker run --rm task4_2 python3 -m pytest tests/cfpq/test.py
