name: CI
on:
  push:
    branches: [ task1 ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: docker build -t task1 .
      - name: Test pygraphblas
        run: docker run --rm task1 pytest tests_pygraphblas/main.py
      - name: Test pyformlang
        run: docker run --rm task1 pytest tests_pyformlang/main.py
