name: CI
on:
  push:
    branches: [ task6 ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: docker build -t task6 .
      - name: Test pygraphblas
        run: docker run --rm task6 python3 -m pytest tests/pygraphblas/test.py
      - name: Test pyformlang
        run: docker run --rm task6 python3 -m pytest tests/pyformlang/test.py
      - name: Test RPQ
        run: docker run --rm task6 python3 -m pytest tests/rpq/test.py
      - name: Test CYK
        run: docker run --rm task6 python3 -m pytest tests/cyk/test.py
      - name: Test CFPQ of Hellings
        run: docker run --rm task6 python3 -m pytest tests/cfpq/test.py
      - name: Test CFPQ through boolean matrices
        run: docker run --rm task6 python3 -m pytest tests/cfpq_bm/test.py
      - name: Test CFPQ through tensor product
        run: docker run --rm task6 python3 -m pytest tests/cfpq_tp/test.py
